[general]
reflect
browser-eyeballs
user-review
factual-mode

[code_development]
extends=general
commit-message
commit-message-this
hostile-review
staff-review
systematic-debugging
bug-hunter

[web_development]
extends=general,code_development
i18n-standards
js-standards
php-documentation-standards
scss-standards
